# Generated by Django 3.0.2 on 2020-03-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('email_id', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=50)),
                ('phoneno', models.IntegerField()),
                ('birthdate', models.DateField(verbose_name='date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='PatientComplaint',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('chief_complaint', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('appointmentdate', models.DateTimeField(max_length=30)),
                ('prescription', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=20)),
                ('d_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('p_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
